name: Terminal Output Workflow

on:
  push:
    branches:
      - main
jobs:
  terminal-output:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Print env
        run: env
