name: Terminal Output Secrets

on:
  push:
    paths:
      - ".github/workflows/02_secrets.yml"
    branches:
      - main
jobs:
  terminal-output:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print MESSGE
        run: echo ${{ secrets.MESSAGE }}
