name: Terminal Output Secrets Workflow

on:
  push:
    paths:
      - ".github/workflows/02_secrets.yml"
    branches:
      - main
jobs:
  secret-output:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Print MESSGE
        run: echo "my secret message is ${{ secrets.MESSAGE }}"
