name: SSH-Agent

on:
  push:
    paths:
      - ".github/workflows/03_ssh-agent.yml"
    branches:
      - main
jobs:
  ssh-agent:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host Key to Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run remote command test
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "touch 'hello-world.txt'"

      - name: Run git clone
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "git clone https://github.com/ragu6963/actions-practice.git"
